name: WHVI
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.2
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - nb_conda
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.3.3
  - python=3.8.5
  - pytorch=1.7.1
  - scikit-learn=0.23.2
  - scipy=1.5.2=py38h14eb087_0
  - setuptools=51.0.0
  - xlrd=1.2.0
  - pip:
    - requests==2.25.1
    - tqdm==4.56.0
    - urllib3==1.26.2